# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: ExecuteTask@2
  inputs:
    ParasoftEMEndpoint: 'CTP - AWS Demo Image'
    Job: 'P1 Smoke Tests'
    PublishDTPReport: true
    ParasoftDTPEndpoint: 'DTP - AWS Demo Image'
    DTPProject: 'Parabank_Master'
    ReportBuildId: '$(Build.BuildId)'
  continueOnError: true

- task: PublishParasoftTestResults@1
  inputs:
    testRunner: 'XTest10x'
    testResultsFiles: '**/report.xml'